version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
